# This is a Kconfig fragment which can be used to enable Segger RTT options.

# Logging
CONFIG_LOG=y

# Console
CONFIG_CONSOLE=y

# segger RTT console
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

# Enable floating point logging
CONFIG_CBPRINTF_FP_SUPPORT=y

# Extra logging for sensor and I2C debugging purposes
CONFIG_SENSOR_LOG_LEVEL_DBG=n
CONFIG_I2C_LOG_LEVEL_DBG=n

CONFIG_LOG_BUFFER_SIZE=512
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=512

CONFIG_LOG_MODE_DEFERRED=n
